/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import javax.swing.JDialog;

/**
 *
 * @author Nemanja
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setTitle("Main");
        setExtendedState(MAXIMIZED_BOTH);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuWorker = new javax.swing.JMenu();
        miWorkerNew = new javax.swing.JMenuItem();
        miWorkerView = new javax.swing.JMenuItem();
        menuRaspberryBush = new javax.swing.JMenu();
        miRaspberryBushNew = new javax.swing.JMenuItem();
        menuPicking = new javax.swing.JMenu();
        miPickingNew = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome to the raspberry picking administration app!");
        lblWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLogout.setText("Log out");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(70, 23));
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        menuWorker.setText("Worker");

        miWorkerNew.setText("New");
        miWorkerNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miWorkerNewActionPerformed(evt);
            }
        });
        menuWorker.add(miWorkerNew);

        miWorkerView.setText("View");
        miWorkerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miWorkerViewActionPerformed(evt);
            }
        });
        menuWorker.add(miWorkerView);

        jMenuBar1.add(menuWorker);

        menuRaspberryBush.setText("RaspberryBush");

        miRaspberryBushNew.setText("New");
        miRaspberryBushNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRaspberryBushNewActionPerformed(evt);
            }
        });
        menuRaspberryBush.add(miRaspberryBushNew);

        jMenuBar1.add(menuRaspberryBush);

        menuPicking.setText("Picking");

        miPickingNew.setText("New");
        miPickingNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPickingNewActionPerformed(evt);
            }
        });
        menuPicking.add(miPickingNew);

        jMenuBar1.add(menuPicking);

        menuAbout.setText("About");
        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(765, 765, 765)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(478, 478, 478))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miWorkerNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miWorkerNewActionPerformed
        lblWelcome.setText(null);
        btnLogout.setVisible(false);
        JDialog dialog = new FrmWorker(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        lblWelcome.setText("Welcome to the raspberry picking administration app!");
        btnLogout.setVisible(true);
    }//GEN-LAST:event_miWorkerNewActionPerformed

    private void miRaspberryBushNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRaspberryBushNewActionPerformed
        lblWelcome.setText(null);
        btnLogout.setVisible(false);
        JDialog dialog = new FrmRaspberryBush(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        lblWelcome.setText("Welcome to the raspberry picking administration app!");
        btnLogout.setVisible(true);
    }//GEN-LAST:event_miRaspberryBushNewActionPerformed

    private void miPickingNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPickingNewActionPerformed
        lblWelcome.setText(null);
        btnLogout.setVisible(false);
        JDialog dialog = new FrmPicking(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        lblWelcome.setText("Welcome to the raspberry picking administration app!");
        btnLogout.setVisible(true);
    }//GEN-LAST:event_miPickingNewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void miWorkerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miWorkerViewActionPerformed
        lblWelcome.setText(null);
        btnLogout.setVisible(false);
        JDialog dialog = new FrmViewWorkers(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        lblWelcome.setText("Welcome to the raspberry picking administration app!");
        btnLogout.setVisible(true);
    }//GEN-LAST:event_miWorkerViewActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuPicking;
    private javax.swing.JMenu menuRaspberryBush;
    private javax.swing.JMenu menuWorker;
    private javax.swing.JMenuItem miPickingNew;
    private javax.swing.JMenuItem miRaspberryBushNew;
    private javax.swing.JMenuItem miWorkerNew;
    private javax.swing.JMenuItem miWorkerView;
    // End of variables declaration//GEN-END:variables
}
