/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Place;
import rs.ac.bg.fon.ps.domain.Worker;
import rs.ac.bg.fon.ps.exception.FirstnameWorkerException;
import rs.ac.bg.fon.ps.exception.LastnameWorkerException;
import rs.ac.bg.fon.ps.exception.TotalWorkerException;
import rs.ac.bg.fon.ps.exception.WorkerException;
import rs.ac.bg.fon.ps.exception.WorkerIdException;

/**
 *
 * @author Nemanja
 */
public class FrmWorker extends javax.swing.JDialog {

    /**
     * Creates new form FrmWorker
     */
    public FrmWorker(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
            setTitle("New Worker");
            setLocationRelativeTo(this);
            prepareView();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View workers form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            throw e;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPlace = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWorkerID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        lblWorkerIdError = new javax.swing.JLabel();
        lblLastnameError = new javax.swing.JLabel();
        lblFirstnameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Worker"));

        jLabel1.setText("Place:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblFirstname.setText("Firstname:");

        lblLastname.setText("Lastname:");

        jLabel2.setText("Worker ID:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblWorkerIdError.setForeground(new java.awt.Color(255, 51, 51));

        lblLastnameError.setForeground(new java.awt.Color(255, 51, 51));

        lblFirstnameError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblFirstname)
                            .addComponent(lblLastname)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstnameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastnameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWorkerID)
                            .addComponent(lblWorkerIdError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 353, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWorkerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkerIdError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFirstnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLastnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Worker worker = new Worker();
            validateWorker();
            worker.setWorkerId(Long.parseLong(txtWorkerID.getText().trim()));
            validateWorker();
            worker.setFirstName(txtFirstname.getText().trim());
            validateWorker();validateWorker();
            worker.setLastName(txtLastname.getText().trim());
            validateWorker();
            worker.setPlace((Place) cmbPlace.getSelectedItem());
            Controller.getInstance().addWorker(worker);
            JOptionPane.showMessageDialog(this, "Worker successfully saved!", "Insert worker", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
        } catch (WorkerIdException wie) {
            wie.printStackTrace();
            JOptionPane.showMessageDialog(this, wie.getInncorrect_workerId(), "Insert worker", JOptionPane.ERROR_MESSAGE);
        } catch (FirstnameWorkerException fwe) {
            fwe.printStackTrace();
            JOptionPane.showMessageDialog(this, fwe.getInncorrect_firstnameWorker(), "Insert worker", JOptionPane.ERROR_MESSAGE);
        } catch (LastnameWorkerException lwe) {
            lwe.printStackTrace();
            JOptionPane.showMessageDialog(this, lwe.getInncorrect_lastnameWorker(), "Insert worker", JOptionPane.ERROR_MESSAGE);
        } catch (TotalWorkerException twe) {
            twe.printStackTrace();
            JOptionPane.showMessageDialog(this, twe.getInncorrect_totalWorker(), "Insert worker", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Worker not saved!", "Insert worker", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cmbPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFirstnameError;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblLastnameError;
    private javax.swing.JLabel lblWorkerIdError;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtWorkerID;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        fillCbPlace();
    }

    private void fillCbPlace() {
        cmbPlace.removeAllItems();
        List<Place> places = Controller.getInstance().getAllPlaces();
        for(Place place : places){
            cmbPlace.addItem(place);
        }
    }
    
    private void resetForm() {
        txtWorkerID.setText("");
        txtFirstname.setText("");
        txtLastname.setText("");
    }
    
    private void validateWorker()throws Exception{
        String errorMessage = "";
        if(txtWorkerID.getText().isEmpty() && txtFirstname.getText().isEmpty() && txtLastname.getText().isEmpty()){
            lblWorkerIdError.setText("Worker ID can not be empty!");
            lblFirstnameError.setText("Firstname can not be empty!");
            lblLastnameError.setText("Lastname can not be empty!");
            errorMessage += "Worker ID can not be empty!\nFirstname can not be empty!\nLastname can not be empty!\n";
            throw new TotalWorkerException(errorMessage);
        }
        if(txtWorkerID.getText().isEmpty() && txtFirstname.getText().isEmpty()){
            lblLastnameError.setText("");
            lblWorkerIdError.setText("Worker ID can not be empty!");
            lblFirstnameError.setText("Firstname can not be empty!");
            errorMessage += "Worker ID can not be empty!\nFirstname can not be empty!";
            throw new TotalWorkerException(errorMessage);
        }
        if(txtWorkerID.getText().isEmpty() && txtLastname.getText().isEmpty()){
            lblFirstnameError.setText("");
            lblWorkerIdError.setText("Worker ID can not be empty!");
            lblLastnameError.setText("Lastname can not be empty!");
            errorMessage += "Worker ID can not be empty!\nLastname can not be empty!\n";
            throw new TotalWorkerException(errorMessage);
        }
        if(txtFirstname.getText().isEmpty() && txtLastname.getText().isEmpty()){
            lblWorkerIdError.setText("");
            lblFirstnameError.setText("Firstname can not be empty!");
            lblLastnameError.setText("Lastname can not be empty!");
            errorMessage += "Firstname can not be empty!\nLastname can not be empty!\n";
            throw new TotalWorkerException(errorMessage);
        }
        if(txtWorkerID.getText().isEmpty()){
            lblWorkerIdError.setText("Worker ID can not be empty!");
            lblFirstnameError.setText("");
            lblLastnameError.setText("");
            errorMessage += "Worker ID can not be empty!\n";
            throw new WorkerIdException(errorMessage);
        }else{
            lblWorkerIdError.setText("");
        }
        if(txtFirstname.getText().isEmpty()){
            lblWorkerIdError.setText("");
            lblFirstnameError.setText("Firstname can not be empty!");
            lblLastnameError.setText("");
            errorMessage += "Firstname can not be empty!\n";
            throw new FirstnameWorkerException(errorMessage);
        }else{
            lblFirstnameError.setText("");
        }
        if(txtLastname.getText().isEmpty()){
            lblWorkerIdError.setText("");
            lblFirstnameError.setText("");
            lblLastnameError.setText("Lastname can not be empty!");
            errorMessage += "Lastname can not be empty!\n";
            throw new LastnameWorkerException(errorMessage);
        }else{
            lblLastnameError.setText("");
        }
        if(!errorMessage.isEmpty()){
            throw new Exception(errorMessage);
        }
    }
}
